# Generated by Django 3.2.6 on 2021-10-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('is_parent', models.BooleanField()),
                ('status', models.IntegerField(default=0)),
                ('priority_index', models.IntegerField()),
                ('child_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
