# Generated by Django 3.2.6 on 2021-10-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211027_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='child_task',
        ),
        migrations.AddField(
            model_name='task',
            name='child_task',
            field=models.ManyToManyField(blank=True, null=True, related_name='_app_task_child_task_+', to='app.Task'),
        ),
    ]
