# Generated by Django 3.2.6 on 2021-11-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211029_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='general_status',
            field=models.CharField(default='today', max_length=10),
            preserve_default=False,
        ),
    ]
